adapt policy to APIM 3.15+
gravitee-io/gravitee-policy-traffic-shadowing pull request #20
Opened 2022-11-23 09:52 UTC by phiz71

**Issue**

gravitee-io/issues#8385

**Description**

bump gravitee-parent, gravitee-common, gravitee-gateway-api and adapt code.

---
**Gravitee.io Automatic Deployment**

🚀 A prerelease version of this package has been published on Gravitee's private artifactory, you can:
 - use it directly by updating your project with version: `2.0.0-adapt-3-15-x-SNAPSHOT`
 - download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/policy/gravitee-policy-traffic-shadowing/2.0.0-adapt-3-15-x-SNAPSHOT/gravitee-policy-traffic-shadowing-2.0.0-adapt-3-15-x-SNAPSHOT.zip)

2022-11-23 13:20 UTC, jhaeyaert requested changes
I've made some propositions to improve the resilience.
If implemented, they should be documented.

2022-11-23 13:20 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/trafficshadowing/TrafficShadowingPolicy.java
> +                            ex.printStackTrace();
⚠️

2022-11-23 13:20 UTC, jhaeyaert commented on src/main/java/io/gravitee/policy/trafficshadowing/TrafficShadowingPolicy.java
> +                chunkBuffers.add(chunk);
We should calculate the total retained size here (ie sum buffer.length) and if it exceed a certain size, just give up to preserve memory (maybe log a warn)

2023-03-08 15:01 UTC, a-cordier commented
see https://github.com/gravitee-io/gravitee-policy-traffic-shadowing/pull/21

2023-03-08 15:01 UTC, closed without merging